version: '3'
services:
  swagger-editor:
    platform: linux/x86_64
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8010:8080"
    volumes:
      - ./components:/components
      - ./model:/model
      - ./paths:/paths
      - ./swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_FILE: /swagger.yaml

  swagger-ui:
    platform: linux/x86_64
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8011:8080"
    volumes:
      - ./components:/components
      - ./model:/model
      - ./paths:/paths
      - ./swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

  swagger-api:
    platform: linux/x86_64
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8012:4010"
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./components:/components
      - ./model:/model
      - ./paths:/paths
      - ./swagger.yaml:/swagger.yaml
