openapi: 3.0.0
info:
  title: RegisterCompany
  version: 1.0.0
  description: separated file
paths:
components:
  schemas:
    RegisterCompanyRequest:
      type: object
      required: [ email, companyName, location ]
      properties:
        email: { type: string, example: support.contact@example.com }
        companyName: { type: string, example: sample-company }
        location: { type: string, example: somewhere }