openapi: 3.0.0
info:
  title: separated file
  version: 1.0.0
  description: separated file
paths:
  /company_register:
    post:
      security:
        - bearerAuth: []
      tags:
        - company/register
      operationId: postCompanyRegister
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/RegisterCompanyRequest'
      responses:
        '200':
          description: '200'
          security:
            - bearerAuth: []
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers200'
        '400':
          description: '400'
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers400'
        '401':
          description: '401'
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers401'
        '404':
          description: '404'
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers404'
        '409':
          description: '409'
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers409'
        '500':
          description: '500'
          headers:
            $ref: '../../components/headers/status-code_error-message.yaml#/components/schemas/Headers500'
components:
  schemas:
    RegisterCompanyRequest:
      $ref: '../../components/authorized/company.yaml#/components/schemas/RegisterCompanyRequest'